#!/bin/bash
# Test making dictionaries and sentence index on plaintext files.

# Absolute path to this file's dir.
SCRIPTDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# Clean up old output from running the test.
rm $SCRIPTDIR/test-data/tokens.dict 2> /dev/null
rm $SCRIPTDIR/test-data/relations.dict 2> /dev/null
rm $SCRIPTDIR/test-data/sentences.index 2> /dev/null

# Run program in question: first to make dictionaries, then to index sentences.
go run *.go \
	plain dict $SCRIPTDIR/test-data/plain-input-paths.txt $SCRIPTDIR/test-data
go run *.go \
	plain index $SCRIPTDIR/test-data/plain-input-paths.txt $SCRIPTDIR/test-data

